{{-- Tailwind CSS via CDN (ganti dengan @vite jika sudah setup) --}}
<script src="https://cdn.tailwindcss.com?plugins=forms,container-queries"></script>
<script>
    tailwind.config = {
        darkMode: "class",
        theme: {
            extend: {
                colors: {
                    "tertiary-fixed": "#d8e2ff",
                    "on-tertiary-fixed-variant": "#004395",
                    "primary-container": "#f97316",
                    "surface-dim": "#cbdbf5",
                    "on-tertiary-fixed": "#001a42",
                    "on-primary-fixed": "#341100",
                    "on-primary": "#ffffff",
                    "secondary-fixed-dim": "#bec6e0",
                    "secondary-container": "#dae2fd",
                    "tertiary-container": "#6399ff",
                    "on-secondary-fixed": "#131b2e",
                    "error-container": "#ffdad6",
                    "surface-container": "#e5eeff",
                    "surface-variant": "#d3e4fe",
                    "on-secondary": "#ffffff",
                    "secondary-fixed": "#dae2fd",
                    "on-surface": "#0b1c30",
                    "background": "#f8f9ff",
                    "surface-tint": "#9d4300",
                    "inverse-surface": "#213145",
                    "primary-fixed": "#ffdbca",
                    "inverse-primary": "#ffb690",
                    "inverse-on-surface": "#eaf1ff",
                    "surface": "#f8f9ff",
                    "surface-container-low": "#eff4ff",
                    "surface-container-high": "#dce9ff",
                    "surface-container-highest": "#d3e4fe",
                    "surface-bright": "#f8f9ff",
                    "secondary": "#565e74",
                    "on-tertiary": "#ffffff",
                    "tertiary": "#005ac2",
                    "on-primary-fixed-variant": "#783200",
                    "primary": "#9d4300",
                    "on-background": "#0b1c30",
                    "on-error": "#ffffff",
                    "on-error-container": "#93000a",
                    "outline-variant": "#e0c0b1",
                    "error": "#ba1a1a",
                    "outline": "#8c7164",
                    "on-primary-container": "#582200",
                    "on-secondary-fixed-variant": "#3f465c",
                    "on-surface-variant": "#584237",
                    "on-secondary-container": "#5c647a",
                    "on-tertiary-container": "#00306e",
                },
                spacing: {
                    "xs":  "4px",
                    "sm":  "8px",
                    "md":  "16px",
                    "lg":  "24px",
                    "xl":  "32px",
                    "xxl": "64px",
                    "gutter": "24px",
                    "container-max": "1280px",
                },
                fontFamily: {
                    "display-lg":        ["Plus Jakarta Sans"],
                    "display-lg-mobile": ["Plus Jakarta Sans"],
                    "headline-lg":       ["Plus Jakarta Sans"],
                    "headline-md":       ["Plus Jakarta Sans"],
                    "body-lg":           ["Inter"],
                    "body-md":           ["Inter"],
                    "label-md":          ["Inter"],
                    "label-sm":          ["Inter"],
                },
                fontSize: {
                    "display-lg":         ["64px",  { lineHeight: "72px",  letterSpacing: "-0.02em", fontWeight: "800" }],
                    "display-lg-mobile":  ["40px",  { lineHeight: "48px",  letterSpacing: "-0.02em", fontWeight: "800" }],
                    "headline-lg":        ["48px",  { lineHeight: "56px",  letterSpacing: "-0.01em", fontWeight: "700" }],
                    "headline-lg-mobile": ["32px",  { lineHeight: "40px",  letterSpacing: "-0.01em", fontWeight: "700" }],
                    "headline-md":        ["30px",  { lineHeight: "38px",  fontWeight: "700" }],
                    "body-lg":            ["18px",  { lineHeight: "28px",  fontWeight: "400" }],
                    "body-md":            ["16px",  { lineHeight: "24px",  fontWeight: "400" }],
                    "label-md":           ["14px",  { lineHeight: "20px",  letterSpacing: "0.05em", fontWeight: "600" }],
                    "label-sm":           ["12px",  { lineHeight: "16px",  fontWeight: "500" }],
                },
            }
        }
    }
</script>
